version: "3.2"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./containers_data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - default
      - web
    labels:
      - "traefik.http.routers.rcp_phpmyadmin.rule=Host(`phpmyadmin.rcp.linkable.tech`)"
      - "traefik.http.routers.rcp_phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.rcp_phpmyadmin.tls=true"
      - "traefik.http.routers.rcp_phpmyadmin.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_phpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    networks:
      - default
      - web
    volumes:
      # - ./backend/public/:/usr/src/app/public
      - ./backend/route/:/usr/src/app/route
      - ./backend/index.js:/usr/src/app/index.js
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    labels:
      - "traefik.http.routers.rcp_backend.rule=Host(`rcp.linkable.tech`) && PathPrefix(`/api`)"
      - "traefik.http.routers.rcp_backend.entrypoints=websecure"
      - "traefik.http.routers.rcp_backend.tls=true"
      - "traefik.http.routers.rcp_backend.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_backend.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    tty: true
    networks:
      - web
    environment:
      PORT: 80
    volumes:
      # - ./frontend/src/public/:/usr/src/app/src/public
      - ./frontend/src/:/usr/src/app/src/
    labels:
      - "traefik.http.routers.rcp_frontend.rule=Host(`rcp.linkable.tech`)"
      - "traefik.http.routers.rcp_frontend.entrypoints=websecure"
      - "traefik.http.routers.rcp_frontend.tls=true"
      - "traefik.http.routers.rcp_frontend.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
  default:
