version: "3.2"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./containers_data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - default
      - web
    labels:
      - "traefik.http.routers.rcp_phpmyadmin.rule=Host(`phpmyadmin.rcp.linkable.tech`)"
      - "traefik.http.routers.rcp_phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.rcp_phpmyadmin.tls=true"
      - "traefik.http.routers.rcp_phpmyadmin.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_phpmyadmin.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    networks:
      - default
      - web
    volumes:
      - ./backend/temp/:/temp/
      - ./backend/route/:/usr/src/app/route
      - ./backend/index.js:/usr/src/app/index.js
    depends_on:
      - db
    environment:
      # DEBUG: socket.io*
      DB_HOST: db
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PUBLIC_VAPID_KEY: BIZeNc9nnXDI_hw--el-oOna4tc2SDAFCMXDmDM4229ZTwrmg9KMgATfF4lcMNnr-yM855TLSxc8cbTyyAqIDBY
      PRIVATE_VAPID_KEY: 9lb6HYYPfsMNZpdWz0yDfS-f0V6zbMmB_WlyuWCVQkk
      WEB_PUSH_CONTACT: url:rcp.linkable.tech
      JWT_KEY: bkNf0YIluD8lOM3Z78Go12AbIczq32Px
    labels:
      - "traefik.http.routers.rcp_backend.rule=Host(`rcp.linkable.tech`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.rcp_backend.entrypoints=websecure"
      - "traefik.http.routers.rcp_backend.tls=true"
      - "traefik.http.routers.rcp_backend.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_backend.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    tty: true
    networks:
      - web
    environment:
      PORT: 80
      PUBLIC_URL: https://rcp.linkable.tech
      REACT_APP_API_URL: https://rcp.linkable.tech
      REACT_APP_PUBLIC_VAPID_KEY: BIZeNc9nnXDI_hw--el-oOna4tc2SDAFCMXDmDM4229ZTwrmg9KMgATfF4lcMNnr-yM855TLSxc8cbTyyAqIDBY
    volumes:
      - ./frontend/public/:/usr/src/app/public
      - ./frontend/src/:/usr/src/app/src/
    labels:
      - "traefik.http.routers.rcp_frontend.rule=Host(`rcp.linkable.tech`)"
      - "traefik.http.routers.rcp_frontend.entrypoints=websecure"
      - "traefik.http.routers.rcp_frontend.tls=true"
      - "traefik.http.routers.rcp_frontend.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=web"

  # media-server:
  #   build:
  #     context: ./media-server
  #   volumes:
  #     - ./media-server/index.js:/usr/src/app/index.js
  #     - ./media-server/create-playlist.js:/usr/src/app/create-playlist.js
  #     - ./media/:/usr/src/app/media/
  #   networks:
  #     - web
  #   ports:
  #     - 8001:80
  #     - 1936:1935
  #   environment:
  #     PUBLISH_START_NOTIFY_URL: ""
  #     PUBLISH_STOP_NOTIFY_URL: ""
  #   labels:
  #     - "traefik.http.routers.rcp_media_server.rule=Host(`rcp.linkable.tech`) && PathPrefix(`/live`)"
  #     - "traefik.http.routers.rcp_media_server.entrypoints=websecure"
  #     - "traefik.http.routers.rcp_media_server.tls=true"
  #     - "traefik.http.routers.rcp_media_server.tls.certresolver=leresolver"
  #     - "traefik.http.services.rcp_media_server.loadbalancer.server.port=80"
  #     - "traefik.docker.network=web"

  media-server:
    build:
      context: ./rtmp-hls-server
    volumes:
      # - ./media-server/index.js:/usr/src/app/index.js
      # - ./media-server/create-playlist.js:/usr/src/app/create-playlist.js
      - ./media-nginx/:/mnt/
    networks:
      - web
    ports:
      - 8080:8080
      - 1937:1935
    labels:
      - "traefik.http.routers.rcp_media_server.rule=Host(`rcp.linkable.tech`) && PathPrefix(`/hls`)"
      - "traefik.http.routers.rcp_media_server.entrypoints=websecure"
      - "traefik.http.routers.rcp_media_server.tls=true"
      - "traefik.http.routers.rcp_media_server.tls.certresolver=leresolver"
      - "traefik.http.services.rcp_media_server.loadbalancer.server.port=8080"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
  default:
